"""autogenerated by genpy from rosmln/MLNInterfaceRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rosmln.msg

class MLNInterfaceRequest(genpy.Message):
  _md5sum = "62568d74f21c9322ed52fdd3d72d116d"
  _type = "rosmln/MLNInterfaceRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """MLNQuery query
MLNConfig config

================================================================================
MSG: rosmln/MLNQuery
string queries


================================================================================
MSG: rosmln/MLNConfig
string mlnFiles
string db
string method
string engine
string output_filename
bool saveResults
string logic
string grammar

"""
  __slots__ = ['query','config']
  _slot_types = ['rosmln/MLNQuery','rosmln/MLNConfig']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       query,config

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MLNInterfaceRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.query is None:
        self.query = rosmln.msg.MLNQuery()
      if self.config is None:
        self.config = rosmln.msg.MLNConfig()
    else:
      self.query = rosmln.msg.MLNQuery()
      self.config = rosmln.msg.MLNConfig()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.query.queries
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.mlnFiles
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.db
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.method
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.engine
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.output_filename
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.config.saveResults))
      _x = self.config.logic
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.grammar
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.query is None:
        self.query = rosmln.msg.MLNQuery()
      if self.config is None:
        self.config = rosmln.msg.MLNConfig()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.query.queries = str[start:end].decode('utf-8')
      else:
        self.query.queries = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.mlnFiles = str[start:end].decode('utf-8')
      else:
        self.config.mlnFiles = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.db = str[start:end].decode('utf-8')
      else:
        self.config.db = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.method = str[start:end].decode('utf-8')
      else:
        self.config.method = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.engine = str[start:end].decode('utf-8')
      else:
        self.config.engine = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.output_filename = str[start:end].decode('utf-8')
      else:
        self.config.output_filename = str[start:end]
      start = end
      end += 1
      (self.config.saveResults,) = _struct_B.unpack(str[start:end])
      self.config.saveResults = bool(self.config.saveResults)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.logic = str[start:end].decode('utf-8')
      else:
        self.config.logic = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.grammar = str[start:end].decode('utf-8')
      else:
        self.config.grammar = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.query.queries
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.mlnFiles
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.db
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.method
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.engine
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.output_filename
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.config.saveResults))
      _x = self.config.logic
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.config.grammar
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.query is None:
        self.query = rosmln.msg.MLNQuery()
      if self.config is None:
        self.config = rosmln.msg.MLNConfig()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.query.queries = str[start:end].decode('utf-8')
      else:
        self.query.queries = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.mlnFiles = str[start:end].decode('utf-8')
      else:
        self.config.mlnFiles = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.db = str[start:end].decode('utf-8')
      else:
        self.config.db = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.method = str[start:end].decode('utf-8')
      else:
        self.config.method = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.engine = str[start:end].decode('utf-8')
      else:
        self.config.engine = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.output_filename = str[start:end].decode('utf-8')
      else:
        self.config.output_filename = str[start:end]
      start = end
      end += 1
      (self.config.saveResults,) = _struct_B.unpack(str[start:end])
      self.config.saveResults = bool(self.config.saveResults)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.logic = str[start:end].decode('utf-8')
      else:
        self.config.logic = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.config.grammar = str[start:end].decode('utf-8')
      else:
        self.config.grammar = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
"""autogenerated by genpy from rosmln/MLNInterfaceResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rosmln.msg

class MLNInterfaceResponse(genpy.Message):
  _md5sum = "2178741cf410384187aa8e9ebc5ba8ae"
  _type = "rosmln/MLNInterfaceResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """MLNDatabase response


================================================================================
MSG: rosmln/MLNDatabase
AtomProbPair[] evidence

================================================================================
MSG: rosmln/AtomProbPair
string atom
float32 prob

"""
  __slots__ = ['response']
  _slot_types = ['rosmln/MLNDatabase']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       response

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MLNInterfaceResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.response is None:
        self.response = rosmln.msg.MLNDatabase()
    else:
      self.response = rosmln.msg.MLNDatabase()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.response.evidence)
      buff.write(_struct_I.pack(length))
      for val1 in self.response.evidence:
        _x = val1.atom
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_f.pack(val1.prob))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.response is None:
        self.response = rosmln.msg.MLNDatabase()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.response.evidence = []
      for i in range(0, length):
        val1 = rosmln.msg.AtomProbPair()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.atom = str[start:end].decode('utf-8')
        else:
          val1.atom = str[start:end]
        start = end
        end += 4
        (val1.prob,) = _struct_f.unpack(str[start:end])
        self.response.evidence.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.response.evidence)
      buff.write(_struct_I.pack(length))
      for val1 in self.response.evidence:
        _x = val1.atom
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_f.pack(val1.prob))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.response is None:
        self.response = rosmln.msg.MLNDatabase()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.response.evidence = []
      for i in range(0, length):
        val1 = rosmln.msg.AtomProbPair()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.atom = str[start:end].decode('utf-8')
        else:
          val1.atom = str[start:end]
        start = end
        end += 4
        (val1.prob,) = _struct_f.unpack(str[start:end])
        self.response.evidence.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_f = struct.Struct("<f")
class MLNInterface(object):
  _type          = 'rosmln/MLNInterface'
  _md5sum = '4d059bedd2ff0f23f7c969691f98ba7f'
  _request_class  = MLNInterfaceRequest
  _response_class = MLNInterfaceResponse
